# Generated by Django 4.1.4 on 2022-12-27 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_activity_enddate_activity_endtime_activity_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 27, 6, 11, 7, 865130, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='activity',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2022, 12, 27, 6, 11, 7, 865130, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='activity',
            name='frequency',
            field=models.CharField(default='hi', max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 27, 6, 11, 7, 865130, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2022, 12, 27, 6, 11, 7, 865130, tzinfo=datetime.timezone.utc)),
        ),
    ]
