# Generated by Django 4.1.4 on 2022-12-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_activity_enddate_alter_activity_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='endTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='frequency',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startTime',
            field=models.TimeField(),
        ),
    ]
