# Generated by Django 4.1.4 on 2022-12-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_activity_thumbnail_alter_activity_enddate_and_more'),
        ('main', '0004_alter_activity_enddate_alter_activity_endtime_and_more'),
    ]

    operations = [
    ]
