# Generated by Django 4.1.4 on 2023-01-01 04:02

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('main', '0004_activity_thumbnail_alter_activity_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='price',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
