# Generated by Django 4.1.4 on 2023-01-01 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_activity_price_activity_tags'),
        ('main', '0005_merge_20221229_2259'),
    ]

    operations = [
    ]
