# Generated by Django 4.1.4 on 2023-01-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_merge_20221231_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='days_of_week',
            field=models.ManyToManyField(to='main.day'),
        ),
    ]
