# Generated by Django 4.1.4 on 2023-01-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_difficulty_activity_activitypage_activity_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Difficulty',
        ),
        migrations.AlterField(
            model_name='activity',
            name='days_of_week',
            field=models.ManyToManyField(related_name='activities', to='main.day'),
        ),
    ]
