# Generated by Django 4.1.4 on 2023-01-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_difficulty_alter_activity_days_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='days_of_week',
            field=models.ManyToManyField(related_name='activty_list', to='main.day'),
        ),
    ]
